name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Чтобы анализировать всю историю коммитов
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2.1.0
        with:
          projectBaseDir: .
          args: >
           -Dsonar.projectKey=Pentrick-star_frontend-project-44
           -Dsonar.organization=pentrick-star
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
